### ISSUE TITLE
[Question] In which order does OreTweaker generate ores?

### ISSUE THREAD

**Issue by laureegrd** [EwyBoy/OreTweaker#33] opened 2021-09-17 03:31 UTC
Hi, I'm using OreTweaker and I wondered if there's any way to known and manipulate the order in which it generates my ores.
Is it alphabetically by filename? Do multiple entries inside a single .json generate from the top first?
Of course, this is important because if I'm generating coal ore first, I'm removing stone blocks that could've been selected by the next ores on the list.
This would mean that each "spawnRate point" is less powerful the later that ore generates if I'm not mistaken.

**Comment by PandaBoy444** [comment] 2021-09-20 16:12
I'm wondering about order as well for a different reason. I want to replace lower levels of earth with deepslate then replace deepslate with ores (ie use deepslate as filler) but not sure if deepslate will generate before the ores.

**Comment by laureegrd** [comment] 2021-09-21 07:35
> 
> 
> I'm wondering about order as well for a different reason. I want to replace lower levels of earth with deepslate then replace deeps

did you try in different ways? Maybe by testing alone you can shed some light onto this topic. My use case is a bit harder to test haha

**Comment by PandaBoy444** [comment] 2021-09-22 10:55
Sorry haven't done so yet. Because I need to restart the game to test it it's less fun to tinker and test so I avoid it. Will probably test this weekend tho

**Comment by laureegrd** [comment] 2021-09-22 20:19
yeah

> 
> 
> Sorry haven't done so yet. Because I need to restart the game to test it it's less fun to tinker and test so I avoid it. Will probably test this weekend tho

yeah i know what you mean, I've been tweaking things for days then I dropped it when I was finally being close to finishing ore generation for my pack lol

**Comment by PandaBoy444** [comment] 2021-09-23 13:41
@EwyBoy is there a good reason for the need for a full restart?

**Comment by EwyBoy** [comment] 2021-09-23 14:17
> @EwyBoy is there a good reason for the need for a full restart?

I have done several tests and after taking to a bunch of other developers we have confirmed that everything that is using the Minecraft CODEC system requires a full game restart no matter what for new world gen to take function due to Minecraft limitations.
The Minecraft codec system 

Minecraft Codec appears to be a convenient way to serialise and deserialise objects without having to hard code a readNBT() and writeNBT() and handle json objects.

**Comment by EwyBoy** [comment] 2021-09-24 00:01
For the subject about spawn order for ores its a bit hard to say.  
OreTweaker reads the ore files alphabetically and registers em for Minecraft to generate.
But I am not sure in what order Minecraft itself uses when deciding the order to generate the ores in. I will try to figure out.

**Comment by EwyBoy** [comment] 2022-01-31 19:13
Closing this one now.

**Closed by EwyBoy** 2022-01-31 19:13 UTC
Labels: Question
