### ISSUE TITLE
[Feature] use blocktag in block name

### ISSUE THREAD

**Issue by PandaBoy444** [EwyBoy/OreTweaker#34] opened 2021-09-20 16:14 UTC
So that for example I could replace use all stonetypes as filler or generate all ores under a single rule

**Comment by EwyBoy** [comment] 2021-09-20 16:43
Duplicate of #12. Still working on it but very busy at the moment with university. Follow #12 for updates.

**Closed by EwyBoy** 2021-09-20 16:43 UTC
